### ISSUE TITLE
Memory leak? 

### ISSUE THREAD

**Issue by oakcreek** [emperorcal/gdax-tradingbot#5]
Hi, there seems memory leaks when using requests in threads. Memory used by requests to get orderbook at each cycle was not cleared after usage. Can you replace requests with urllib?

**Comment by calum-mcg** [comment]
This project is no longer maintained by myself. I would recommend to fork and update to adopt urllib. Please also note that as of May 2019, the API will be accessed via api.pro.coinbase.com rather than api.gdax.com - _Please visit the Coinbase documentation [here](https://docs.pro.coinbase.com/?r=1)_
